### ISSUE TITLE
jade templates not working for custom visualizations

### ISSUE THREAD

**Issue by brianbreitsch** [lightning-viz/lightning#21]
Here's the server console output:

```
requested url: /visualization-types/preview/full/?path=/home/breitsbw/projects/gnss-viz
Create from folder: /home/breitsbw/projects/gnss-viz
created viz preview
/home/breitsbw/projects/lightning/tmp/js-build/82bdbab8-3e1a-4cbd-950e-6dedabbf1d66/viz//home/breitsbw/projects/gnss-viz.jade
Error: Cannot find module './template.jade' from '/home/breitsbw/projects/lightning/tmp/js-build/82bdbab8-3e1a-4cbd-950e-6dedabbf1d66/viz'
    at /home/breitsbw/projects/lightning/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/breitsbw/projects/lightning/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/breitsbw/projects/lightning/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/breitsbw/projects/lightning/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

The directory structure is:

```
gnss-viz/template.jade
        /index.js
        /sample-data.json
```

The import inside `index.js` looks like `var templateHTML = require('./template.jade');`

I believe this is all in accordance with the Getting Started guide: http://lightning-viz.org/documentation/#custom-template

If I figure anything out, I'll let ya know.
I already tried renaming files to `gnss-viz.js` and `gnss-viz.jade` (it appears that Lightning does this when it creates a temp repo), but to no avail.

**Comment by mathisonian** [comment]
@brianbreitsch the last commit should fix this issue, provided that you name the file `gnss-viz.jade` (name of the js file shouldn't matter).

We are discussing ways to make this whole system more robust, so I guess this can be considered a workaround until we get something better. (This is one of the top priorities for the project at the moment). We can discuss more in gitter, but after discussing with @freeman-lab it seems like the best option may be to treat each visualization as a separate module (in the node/commonjs/npm sense of module) so that each can handle their own dependencies, file structure, etc individually, with lightning providing some basic templates for how to do this. Curious to hear your thoughts.

I'll close this once you confirm that the fix works.
